name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Build with dotnet    
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/ChristianHellwig/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  
    
    - name: Build solution and generate NuGet package
      run: |  
        cd LessPaper.Shared
        dotnet pack -c Release -o out  
    
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./LessPaper.Shared/out/*.nupkg --skip-duplicate --no-symbols true
  
