name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Define runtime   
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    - name: Build solution and generate NuGet package
      run: |  
        cd LessPaper.Shared
        dotnet pack -c Release 
    
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.2.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: LessPaper.Shared/LessPaper.Shared.csproj
        PACKAGE_NAME: LessPaper.Shared
        # API key for the NuGet feed
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}    
